### ISSUE TITLE
Please add a GPL3 LICENSE file and mention that this repo is a copy of https://github.com/CapnBry/CRServoF

### ISSUE THREAD

**Issue by wingunder** [sfjuocekr/CRSF-joystick#1]
This PR refers to: https://github.com/CapnBry/CRServoF/issues/18

This repository is a copy and not a fork of https://github.com/CapnBry/CRServoF.
It however seems as if the LICENSE file went missing. 
Please add a GPL3 LICENSE file and mention that this repository is a copy of https://github.com/CapnBry/CRServoF.

**Comment by sfjuocekr** [comment]
I indeed forgot to add the license.

```
/*
 * CRSF/SBUS USB Joystick by Sjoer van der Ploeg
 *
 * SBUS = Serial1 (pin 0)
 * CRSF = Serial2 (rx pin 9, tx pin 10)
 *
 * Channels 1, 2, 3 and 4 are axis; the rest is assumed to be three position switches.
 * Having separate buttons makes setting up simulator functions a breeze!
 *
 * SBUS from bolderflight: https://github.com/bolderflight/SBUS
 * CrsfSerial from CapnBry: https://github.com/CapnBry/CRServoF/tree/master/lib/CrsfSerial
 */
```

Credits were given not just in that issue, but also in main.cpp at the top.

I personally think CrsfSerial should be moved out of CRServoF as only that class is relevant to my project.

**Comment by wingunder** [comment]
Ok, thanks a lot.
Closing.

**Comment by sfjuocekr** [comment]
No problem, I'm not the person to steal someones hard work without credit <3
