### ISSUE TITLE
Where is SBUS.h?

### ISSUE THREAD

**Issue by marcdornan** [sfjuocekr/CRSF-joystick#2]
I assume this relates to the Sbus library used in this project. I do not see it in the lib folder. It is an available library for PlatformIO: https://registry.platformio.org/libraries/bolderflight/Bolder%20Flight%20Systems%20SBUS

It's probably a very basic question but I am not certain how I am supposed to fix this error.

Why did you not just use: #include <sbus.h> and include the libraries like the crsf?

Appreciate any pointers. A more competent PlatformIO user would probably be able to fix this in 30 seconds.

**Comment by sfjuocekr** [comment]
Yes, you need the BolderFlight SBUS library!

Sorry for the late response, this is mentioned in the readme as well at the bottom.
